package model;


public enum Type {
	
	BOISSONCHAUDE, BOISSONFRAICHE, VIENNOISERIE, PLAT, ASSIETTE , DESSERT,
	
	ASSOCIATE, BUILDER, SILVER, GOLD, PLATINIUM, DIAMOND, BLUE_DIAMOND, BLACK_DIAMOND, CROWN_DIAMOND

}
